### PR TITLE
Number code in search input must not be empty.

### PR DESCRIPTION
**Pull request by cssru**
[Review on Reviewable](https://reviewable.io/reviews/php-coder/mystamps/342)

### CODE REVIEW

**Comment by php-coder** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/main/java/ru/mystamps/web/controller/SeriesController.java, line 352 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/342#-K9ahGLhI4ZfwN5MKPqY:-K9ahGLhI4ZfwN5MKPqZ:1927050633) ([raw file](https://github.com/php-coder/mystamps/blob/9342dff7cd30e2ef3c2a01b3c1899f927713c5f5/src/main/java/ru/mystamps/web/controller/SeriesController.java#L352)):*
After removing `Optional` we need to check for `null`ness also.

---

*[src/main/java/ru/mystamps/web/controller/SeriesController.java, line 361 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/342#-K9ah35xSgklTDjUnRwK:-K9ah35ys414z5NOlqTV:-1869567966) ([raw file](https://github.com/php-coder/mystamps/blob/9342dff7cd30e2ef3c2a01b3c1899f927713c5f5/src/main/java/ru/mystamps/web/controller/SeriesController.java#L361)):*
Ah, don't like this ugly syntax.. Hm... let's get rid of `Optional` usage here, I don't see benefits of using it.

---

*[src/main/resources/ru/mystamps/i18n/Messages.properties, line 47 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/342#-K9agRljEnIeRDmHFh3p:-K9agRljEnIeRDmHFh3q:-397721838) ([raw file](https://github.com/php-coder/mystamps/blob/9342dff7cd30e2ef3c2a01b3c1899f927713c5f5/src/main/resources/ru/mystamps/i18n/Messages.properties#L47)):*
1) It's message for validation, so it should be in `ValidationMessages` file
2) we should modify message to say about what is desired state (must not be empty) instead of current (is empty)
3) I suggest to rename key to `value.empty = Value must not be empty`

---

*[src/main/resources/ru/mystamps/i18n/Messages_ru.properties, line 0 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/342#-K9agw7i6lxRVfFvJQE_:-K9agw7i6lxRVfFvJQEa:-282430900) ([raw file](https://github.com/php-coder/mystamps/blob/9342dff7cd30e2ef3c2a01b3c1899f927713c5f5/src/main/resources/ru/mystamps/i18n/Messages_ru.properties#L0)):*
The same as for English translation.

---

*[src/main/webapp/WEB-INF/views/site/index.html, line 253 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/342#-K9ahWBSbGyUlaJeB5cj:-K9ahWBSbGyUlaJeB5ck:-2042639228) ([raw file](https://github.com/php-coder/mystamps/blob/9342dff7cd30e2ef3c2a01b3c1899f927713c5f5/src/main/webapp/WEB-INF/views/site/index.html#L253)):*
It shouldn't be visible in prototype.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/php-coder/mystamps/342)*

**Comment by cssru** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/main/java/ru/mystamps/web/controller/SeriesController.java, line 352 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/342#-K9ahGLhI4ZfwN5MKPqY:-KA6Nuaa5T6HbEnXZqi_:-499146009) ([raw file](https://github.com/php-coder/mystamps/blob/9342dff7cd30e2ef3c2a01b3c1899f927713c5f5/src/main/java/ru/mystamps/web/controller/SeriesController.java#L352)):*
Done.

---

*[src/main/java/ru/mystamps/web/controller/SeriesController.java, line 361 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/342#-K9ah35xSgklTDjUnRwK:-KA6NqoeOh2lRZfvZGin:-499146009) ([raw file](https://github.com/php-coder/mystamps/blob/9342dff7cd30e2ef3c2a01b3c1899f927713c5f5/src/main/java/ru/mystamps/web/controller/SeriesController.java#L361)):*
Done.

---

*[src/main/webapp/WEB-INF/views/site/index.html, line 253 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/342#-K9ahWBSbGyUlaJeB5cj:-KA6ONhtzgl9Wl7gDzUZ:-499146009) ([raw file](https://github.com/php-coder/mystamps/blob/9342dff7cd30e2ef3c2a01b3c1899f927713c5f5/src/main/webapp/WEB-INF/views/site/index.html#L253)):*
Done.

---

*[src/main/resources/ru/mystamps/i18n/Messages.properties, line 47 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/342#-K9agRljEnIeRDmHFh3p:-KA6MLisBGeyVwl7IX-J:-499146009) ([raw file](https://github.com/php-coder/mystamps/blob/9342dff7cd30e2ef3c2a01b3c1899f927713c5f5/src/main/resources/ru/mystamps/i18n/Messages.properties#L47)):*
Done.

---

*[src/main/resources/ru/mystamps/i18n/Messages_ru.properties, line  \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/342#-K9agw7i6lxRVfFvJQE_:-KA6ORHcQPeHUYrYSVrJ:-499146009) ([raw file](https://github.com/php-coder/mystamps/blob/9342dff7cd30e2ef3c2a01b3c1899f927713c5f5/src/main/resources/ru/mystamps/i18n/Messages_ru.properties#L)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/php-coder/mystamps/342)*

**Comment by php-coder** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/php-coder/mystamps/342)*

**Comment by php-coder** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/ru/mystamps/web/controller/SeriesController.java, line 350 \[r3\]](https://reviewable.io:443/reviews/php-coder/mystamps/342#-KAM6n9Sj3OTGzZCT6Aa:-KAM6n9Sj3OTGzZCT6Ab:-2018485265) ([raw file](https://github.com/php-coder/mystamps/blob/2524d501f14d3d73dc0f58e400915e5fbf48aacc/src/main/java/ru/mystamps/web/controller/SeriesController.java#L350)):*
Может переименовать в `redirectAttributes`?

---

*[src/main/webapp/WEB-INF/views/site/index.html, line 255 \[r3\]](https://reviewable.io:443/reviews/php-coder/mystamps/342#-KAM6WbWylwWf12ENjNn:-KAM6WbWylwWf12ENjNo:-1760080360) ([raw file](https://github.com/php-coder/mystamps/blob/2524d501f14d3d73dc0f58e400915e5fbf48aacc/src/main/webapp/WEB-INF/views/site/index.html#L255)):*
Сообщение в прототипе нужно обновить. Код сообщения также нужно обновить (скорее всего сейчас это не работает).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/php-coder/mystamps/342)*

**Comment by cssru** [comment]
Review status: 2 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/ru/mystamps/web/controller/SeriesController.java, line 350 \[r3\]](https://reviewable.io:443/reviews/php-coder/mystamps/342#-KAM6n9Sj3OTGzZCT6Aa:-KAVb2_4-LGK2PtMpqVV:-499146009) ([raw file](https://github.com/php-coder/mystamps/blob/2524d501f14d3d73dc0f58e400915e5fbf48aacc/src/main/java/ru/mystamps/web/controller/SeriesController.java#L350)):*
Done.

---

*[src/main/webapp/WEB-INF/views/site/index.html, line 255 \[r3\]](https://reviewable.io:443/reviews/php-coder/mystamps/342#-KAM6WbWylwWf12ENjNn:-KAVbKO9dif2Qoe8uIZ4:-499146009) ([raw file](https://github.com/php-coder/mystamps/blob/2524d501f14d3d73dc0f58e400915e5fbf48aacc/src/main/webapp/WEB-INF/views/site/index.html#L255)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/php-coder/mystamps/342)*

**Comment by php-coder** [comment]
Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/php-coder/mystamps/342)*

**Comment by php-coder** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/main/webapp/WEB-INF/views/site/index.html, line 254 \[r4\]](https://reviewable.io:443/reviews/php-coder/mystamps/342#-KAW0v448dvKONan2yih:-KAW0v45mTr9tsK3PbRA:748926526) ([raw file](https://github.com/php-coder/mystamps/blob/bbbdb386214244dd47f9c666ab71de19297e2868/src/main/webapp/WEB-INF/views/site/index.html#L254)):*
Придется чуток переделать: во всех остальных местах при отображении ошибки валидации мы используем:
1) span вместо `div`
2) класс `help-block` вместо `text-danger`
Предлагаю переделать для унификации и идиоматического использования бутстрапа (в этом случае он сам подсветит блок красным, так как его родительский тег имеет класс `has-error`.

Еще чуть-чуть и я замерджу! :)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/php-coder/mystamps/342)*

**Comment by cssru** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/webapp/WEB-INF/views/site/index.html, line 254 \[r4\]](https://reviewable.io:443/reviews/php-coder/mystamps/342#-KAW0v448dvKONan2yih:-KAWTbRGd5xQpNI4KE1S:-499146009) ([raw file](https://github.com/php-coder/mystamps/blob/bbbdb386214244dd47f9c666ab71de19297e2868/src/main/webapp/WEB-INF/views/site/index.html#L254)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/php-coder/mystamps/342)*

**Comment by php-coder** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/php-coder/mystamps/342)*

**Comment by php-coder** [comment]
Thank you for the PR, I've merged it in 0172e38ff93718c20ecbbc0700ab52d132e0028e commit.

**Pull request closed without merging**
