### PR TITLE
Restrict user's permissions for adding images.

### PR DESCRIPTION
**Pull request by cssru**
This change is [Reviewable](https://reviewable.io/reviews/php-coder/mystamps/382)

### CODE REVIEW

**Comment by php-coder** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/main/java/ru/mystamps/web/controller/SeriesController.java, line 256 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/382#-KF8wI2jiZzFZdo4LMIR:-KF8wI2k0lFj9ZPPpFBP:-162174722) ([raw file](https://github.com/php-coder/mystamps/blob/d9142614727b5d35d58b28dcdc44acd2edccee2f/src/main/java/ru/mystamps/web/controller/SeriesController.java#L256)):*
Don't use exceptions for a normal cases, like this. I suggest to return 403 status.

---

*[src/main/java/ru/mystamps/web/controller/SeriesController.java, line 382 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/382#-KF9-0J1MTwa7H7rQncG:-KF9-0J1MTwa7H7rQncH:-1875097821) ([raw file](https://github.com/php-coder/mystamps/blob/7fa1008e95c56ca87ff17a6284b8117dd87d197c/src/main/java/ru/mystamps/web/controller/SeriesController.java#L382)):*
Why did you change it?

---

*[src/main/java/ru/mystamps/web/controller/SeriesController.java, line 402 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/382#-KF9-PoZW_v9IZT0WGah:-KF9-PoZW_v9IZT0WGai:-1238807629) ([raw file](https://github.com/php-coder/mystamps/blob/d9142614727b5d35d58b28dcdc44acd2edccee2f/src/main/java/ru/mystamps/web/controller/SeriesController.java#L402)):*
static

---

*[src/main/java/ru/mystamps/web/controller/SeriesController.java, line 414 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/382#-KF9-NTi45C-pTF3weGd:-KF9-NTi45C-pTF3weGe:-1238807629) ([raw file](https://github.com/php-coder/mystamps/blob/d9142614727b5d35d58b28dcdc44acd2edccee2f/src/main/java/ru/mystamps/web/controller/SeriesController.java#L414)):*
static

---

*[src/main/java/ru/mystamps/web/controller/SeriesController.java, line 418 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/382#-KF8zCT8XGoGy3dwY0on:-KF8zCT9ZdqRGtoPPAJ9:1732572783) ([raw file](https://github.com/php-coder/mystamps/blob/d9142614727b5d35d58b28dcdc44acd2edccee2f/src/main/java/ru/mystamps/web/controller/SeriesController.java#L418)):*
If anonymous user tries to add images to series that (by mistake) don't have an owner, then it will return `true` right?

---

*[src/main/webapp/WEB-INF/views/series/info.html, line 298 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/382#-KF9-bLj3HXZjcpCzx5u:-KF9-bLj3HXZjcpCzx5v:-295026183) ([raw file](https://github.com/php-coder/mystamps/blob/7fa1008e95c56ca87ff17a6284b8117dd87d197c/src/main/webapp/WEB-INF/views/series/info.html#L298)):*
Why did you remove togglz?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/php-coder/mystamps/382)*

**Comment by cssru** [comment]
*[src/main/java/ru/mystamps/web/controller/SeriesController.java, line 256 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/382#-KF8wI2jiZzFZdo4LMIR:-KF94vv8Z3oPOOhOHTdU:1324461357) ([raw file](https://github.com/php-coder/mystamps/blob/d9142614727b5d35d58b28dcdc44acd2edccee2f/src/main/java/ru/mystamps/web/controller/SeriesController.java#L256)):*
It is not normal case. It's suspicious activity, isn'it?
'Cause in normal app execution user will not see interface for adding images.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/php-coder/mystamps/382)*

**Comment by cssru** [comment]
*[src/main/java/ru/mystamps/web/controller/SeriesController.java, line 382 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/382#-KF9-0J1MTwa7H7rQncG:-KF95YjZsXz2rTLxX2J1:937231837) ([raw file](https://github.com/php-coder/mystamps/blob/7fa1008e95c56ca87ff17a6284b8117dd87d197c/src/main/java/ru/mystamps/web/controller/SeriesController.java#L382)):*
Less or equals allows to add quantity+1 image. Equals only does not.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/php-coder/mystamps/382)*

**Comment by cssru** [comment]
*[src/main/java/ru/mystamps/web/controller/SeriesController.java, line 418 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/382#-KF8zCT8XGoGy3dwY0on:-KF96MWinSAxCGQcrhIA:115592000) ([raw file](https://github.com/php-coder/mystamps/blob/d9142614727b5d35d58b28dcdc44acd2edccee2f/src/main/java/ru/mystamps/web/controller/SeriesController.java#L418)):*
Yes. But describe situation when series has no owner. Just for me, please.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/php-coder/mystamps/382)*

**Comment by cssru** [comment]
*[src/main/webapp/WEB-INF/views/series/info.html, line 298 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/382#-KF9-bLj3HXZjcpCzx5u:-KF96feoW7SERxz8ThA0:1142760271) ([raw file](https://github.com/php-coder/mystamps/blob/7fa1008e95c56ca87ff17a6284b8117dd87d197c/src/main/webapp/WEB-INF/views/series/info.html#L298)):*
'Cause you asked for me. Or not? )

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/php-coder/mystamps/382)*

**Comment by php-coder** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[src/main/java/ru/mystamps/web/controller/SeriesController.java, line 256 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/382#-KF8wI2jiZzFZdo4LMIR:-KF9LCU1ru9Cx68dreSb:-529665407) ([raw file](https://github.com/php-coder/mystamps/blob/d9142614727b5d35d58b28dcdc44acd2edccee2f/src/main/java/ru/mystamps/web/controller/SeriesController.java#L256)):*
Yes, and it will be recorded when we will log 403 errors to db (https://github.com/php-coder/mystamps/issues/124). But it's another story.

Right now, please, return 403 status. And I don't mind about writing WARNING to the logs. In this case it also useful to provide user id (and don't forget that it might be `null`).

---

*[src/main/java/ru/mystamps/web/controller/SeriesController.java, line 382 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/382#-KF9-0J1MTwa7H7rQncG:-KF9KSCSiUyndcLRSltJ:-670560513) ([raw file](https://github.com/php-coder/mystamps/blob/7fa1008e95c56ca87ff17a6284b8117dd87d197c/src/main/java/ru/mystamps/web/controller/SeriesController.java#L382)):*
Yes, I know that :) But it wasn't in the task and even if you want to fix it, it should be a separate fix. But you shouldn't fix it, because it's a feature, not a bug: https://github.com/php-coder/mystamps/issues/108

---

*[src/main/java/ru/mystamps/web/controller/SeriesController.java, line 418 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/382#-KF8zCT8XGoGy3dwY0on:-KF9K-u_2qjaY2jUuspv:-1842446657) ([raw file](https://github.com/php-coder/mystamps/blob/d9142614727b5d35d58b28dcdc44acd2edccee2f/src/main/java/ru/mystamps/web/controller/SeriesController.java#L418)):*
I couldn't imagine something realistic, so, I don't mind. But I'm still thinking about corner cases and I'm trying to be defensive against even unknown possible outcomes.

---

*[src/main/java/ru/mystamps/web/support/spring/security/SecurityContextUtils.java, line 47 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/382#-KF9Fjh3u8KONS2xjLQ6:-KF9Fjh3u8KONS2xjLQ7:254395622) ([raw file](https://github.com/php-coder/mystamps/blob/d9142614727b5d35d58b28dcdc44acd2edccee2f/src/main/java/ru/mystamps/web/support/spring/security/SecurityContextUtils.java#L47)):*
Maybe replace last 2 lines to simple `authorities.contains(authority)`? Or it's not the same?

P.S. Aha... I see. Why do we need another one method of checking that user has authority? I suggest to use existing, if you need to access `HttpServletRequest` then declare it as and argument of the controller's method.

---

*[src/main/webapp/WEB-INF/views/series/info.html, line 298 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/382#-KF9-bLj3HXZjcpCzx5u:-KF9G0tZuKNZpU5qbbAe:1084012179) ([raw file](https://github.com/php-coder/mystamps/blob/7fa1008e95c56ca87ff17a6284b8117dd87d197c/src/main/webapp/WEB-INF/views/series/info.html#L298)):*
I don't remember that I asked you to remove togglz feature. Could you point me to my request? (Even if it's true, then you missed to remove this feature from Togglz config).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/php-coder/mystamps/382)*

**Comment by cssru** [comment]
*[src/main/java/ru/mystamps/web/support/spring/security/SecurityContextUtils.java, line 47 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/382#-KF9Fjh3u8KONS2xjLQ6:-KFBGbo9tMpf8-UB8rGY:-1696277963) ([raw file](https://github.com/php-coder/mystamps/blob/d9142614727b5d35d58b28dcdc44acd2edccee2f/src/main/java/ru/mystamps/web/support/spring/security/SecurityContextUtils.java#L47)):*
Of course, i saw old method. I just suggest to use method, which doesn't use unnecessary parameter and doesn't create new objects.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/php-coder/mystamps/382)*

**Comment by cssru** [comment]
*[src/main/java/ru/mystamps/web/support/spring/security/SecurityContextUtils.java, line 47 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/382#-KF9Fjh3u8KONS2xjLQ6:-KFUzJl6CU4xouyQHrkk:1585870140) ([raw file](https://github.com/php-coder/mystamps/blob/d9142614727b5d35d58b28dcdc44acd2edccee2f/src/main/java/ru/mystamps/web/support/spring/security/SecurityContextUtils.java#L47)):*
List<GrantedAuthority>.contains(String)? How it is possible?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/php-coder/mystamps/382)*

**Comment by cssru** [comment]
*[src/main/java/ru/mystamps/web/support/spring/security/SecurityContextUtils.java, line 47 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/382#-KF9Fjh3u8KONS2xjLQ6:-KFUzqjcacDOAKh96Eaa:-1385248225) ([raw file](https://github.com/php-coder/mystamps/blob/d9142614727b5d35d58b28dcdc44acd2edccee2f/src/main/java/ru/mystamps/web/support/spring/security/SecurityContextUtils.java#L47)):*
I mean List with GrantedAuthority

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/php-coder/mystamps/382)*

**Comment by php-coder** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[src/main/java/ru/mystamps/web/support/spring/security/SecurityContextUtils.java, line 47 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/382#-KF9Fjh3u8KONS2xjLQ6:-KFVAGJ8RrFaMzu_xEoG:-872676094) ([raw file](https://github.com/php-coder/mystamps/blob/d9142614727b5d35d58b28dcdc44acd2edccee2f/src/main/java/ru/mystamps/web/support/spring/security/SecurityContextUtils.java#L47)):*
Could you add type to `a` in `anyMatch()`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/php-coder/mystamps/382)*

**Comment by cssru** [comment]
Review status: 6 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/main/java/ru/mystamps/web/controller/SeriesController.java, line 256 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/382#-KF8wI2jiZzFZdo4LMIR:-KFciF1twLV6dAHX9g7R:-499146009) ([raw file](https://github.com/php-coder/mystamps/blob/d9142614727b5d35d58b28dcdc44acd2edccee2f/src/main/java/ru/mystamps/web/controller/SeriesController.java#L256)):*
Done.

---

*[src/main/java/ru/mystamps/web/controller/SeriesController.java, line 382 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/382#-KF9-0J1MTwa7H7rQncG:-KFciQ2-cnciyLg2obG4:-499146009) ([raw file](https://github.com/php-coder/mystamps/blob/7fa1008e95c56ca87ff17a6284b8117dd87d197c/src/main/java/ru/mystamps/web/controller/SeriesController.java#L382)):*
Done.

---

*[src/main/java/ru/mystamps/web/controller/SeriesController.java, line 402 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/382#-KF9-PoZW_v9IZT0WGah:-KFciMdbEEFI8uSkJZSi:-499146009) ([raw file](https://github.com/php-coder/mystamps/blob/d9142614727b5d35d58b28dcdc44acd2edccee2f/src/main/java/ru/mystamps/web/controller/SeriesController.java#L402)):*
Done.

---

*[src/main/java/ru/mystamps/web/controller/SeriesController.java, line 414 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/382#-KF9-NTi45C-pTF3weGd:-KFcj47sRCuAnKhx_wIf:-499146009) ([raw file](https://github.com/php-coder/mystamps/blob/d9142614727b5d35d58b28dcdc44acd2edccee2f/src/main/java/ru/mystamps/web/controller/SeriesController.java#L414)):*
Done.

---

*[src/main/java/ru/mystamps/web/controller/SeriesController.java, line 418 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/382#-KF8zCT8XGoGy3dwY0on:-KFcj6XTvLu7z2rxobQp:-499146009) ([raw file](https://github.com/php-coder/mystamps/blob/d9142614727b5d35d58b28dcdc44acd2edccee2f/src/main/java/ru/mystamps/web/controller/SeriesController.java#L418)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/php-coder/mystamps/382)*

**Comment by php-coder** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/php-coder/mystamps/382)*

**Comment by php-coder** [comment]
In current implementation admin can't add more images. For example, create series with 1 stamp, add 2 images and try to add another one.

**Comment by cssru** [comment]
Ah...I see. Soon it all will be ok )

**Comment by php-coder** [comment]
Merged in ae08224 commit. Thank you!

**Pull request closed without merging**
