### PR TITLE
Togglz boot fix

### PR DESCRIPTION
**Pull request by marceloverdijk**
Hi @php-coder 

Here is the fix for the Togglz Spring Boot Starter.

1. I updated the dep to `togglz-spring-boot-starter`. Please make sure you pull latest code from my repo and install `0.0.1.BUILD-SNAPSHOT`.
2. I disabled the Togglz endpoint (`togglz.endpoint.enabled: false`) as you don't have `spring-boot-starter-actuator` dependency in your project. Note you could also remove the `togglz.endpoint.*` completely in this case. But as it was enabled explicitly the app failed now.

The app starts up fine now!

Cheers,
Marcel

[Review on Reviewable](https://reviewable.io/reviews/php-coder/mystamps/338)

### CODE REVIEW

**Comment by php-coder** [comment]
Thank you for your input!

This branch is mostly for testing and experiments, so it would be merged only when togglz and it's spring-boot integration component will be released. Without that I don't want to make my build unstable by using SNAPSHOTs.

**Comment by marceloverdijk** [comment]
Hi @php-coder yes this PR is only to update this specific `togglz_boot` branch. You shoul dnot merge it to `master`. If you merge it to 'togglz_boot` you can continue your expirement on that branch.

**Comment by marceloverdijk** [comment]
Hmm I think the PR is not correct, as it is trying to merge something to `master` indeed.
The fixes should be merged to `togglz_boot` branch instead.

**Comment by marceloverdijk** [comment]
Obsolute because of correct PR https://github.com/php-coder/mystamps/pull/339

**Pull request closed without merging**
