### PR TITLE
Don't log added catalog numbers when they weren't added.

### PR DESCRIPTION
**Pull request by cssru**
This change is [Reviewable](https://reviewable.io/reviews/php-coder/mystamps/386)

### CODE REVIEW

**Comment by php-coder** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/php-coder/mystamps/386)*

**Comment by php-coder** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/main/java/ru/mystamps/web/service/MichelCatalogServiceImpl.java, line 52 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/386#-KGSa64RBpK4mAPDXcoW:-KGSa64RBpK4mAPDXcoX:-707120526) ([raw file](https://github.com/php-coder/mystamps/blob/a23f821b6927028156bb16deb1304a1981e06460/src/main/java/ru/mystamps/web/service/MichelCatalogServiceImpl.java#L52)):*
! is missing here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/php-coder/mystamps/386)*

**Comment by cssru** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/ru/mystamps/web/service/MichelCatalogServiceImpl.java, line 52 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/386#-KGSa64RBpK4mAPDXcoW:-KGTPj156nVNjv2yODUg:-499146009) ([raw file](https://github.com/php-coder/mystamps/blob/a23f821b6927028156bb16deb1304a1981e06460/src/main/java/ru/mystamps/web/service/MichelCatalogServiceImpl.java#L52)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/php-coder/mystamps/386)*

**Comment by php-coder** [comment]
Merged in ee8836de1cff1429ab48c592d3a0fa9aee3431bc commit.

**Pull request closed without merging**
