### PR TITLE
Update series updated_* fields when adding new image to series.

### PR DESCRIPTION
**Pull request by cssru**
This change is [Reviewable](https://reviewable.io/reviews/php-coder/mystamps/364)

### CODE REVIEW

**Comment by php-coder** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/main/java/ru/mystamps/web/dao/JdbcSeriesDao.java, line 32 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/364#-KE1C-Cx4AxzHJTJ-ilG:-KE1C-Cx4AxzHJTJ-ilH:952974431) ([raw file](https://github.com/php-coder/mystamps/blob/7a944763c43db171a9a0c30577ce8ac93891dde6/src/main/java/ru/mystamps/web/dao/JdbcSeriesDao.java#L32)):*
Rename to `markAsModified()`

---

*[src/main/java/ru/mystamps/web/dao/impl/JdbcSeriesDaoImpl.java, line 59 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/364#-KE1C9UJgnanoYdqT8Yu:-KE1C9UJgnanoYdqT8Yv:-744373176) ([raw file](https://github.com/php-coder/mystamps/blob/7a944763c43db171a9a0c30577ce8ac93891dde6/src/main/java/ru/mystamps/web/dao/impl/JdbcSeriesDaoImpl.java#L59)):*
Need to rename member and name in properties.

---

*[src/main/java/ru/mystamps/web/dao/impl/JdbcSeriesDaoImpl.java, line 154 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/364#-KE1C82iHkdeV6MZ6SgC:-KE1C82iHkdeV6MZ6SgD:952974431) ([raw file](https://github.com/php-coder/mystamps/blob/7a944763c43db171a9a0c30577ce8ac93891dde6/src/main/java/ru/mystamps/web/dao/impl/JdbcSeriesDaoImpl.java#L154)):*
Rename to `markAsModified()`

---

*[src/main/java/ru/mystamps/web/dao/impl/JdbcSeriesDaoImpl.java, line 167 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/364#-KE1CU_s5PjGJlPxRaaG:-KE1CU_s5PjGJlPxRaaH:1125939809) ([raw file](https://github.com/php-coder/mystamps/blob/7a944763c43db171a9a0c30577ce8ac93891dde6/src/main/java/ru/mystamps/web/dao/impl/JdbcSeriesDaoImpl.java#L167)):*
`updating of series` -> `updating series`

---

*[src/main/resources/sql/series_dao_queries.properties, line 48 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/364#-KE1CeBFMDjVRGb8NK_2:-KE1CeBFMDjVRGb8NK_3:-1265256283) ([raw file](https://github.com/php-coder/mystamps/blob/7a944763c43db171a9a0c30577ce8ac93891dde6/src/main/resources/sql/series_dao_queries.properties#L48)):*
Need to be renamed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/php-coder/mystamps/364)*

**Comment by php-coder** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/main/java/ru/mystamps/web/service/SeriesServiceImpl.java, line 166 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/364#-KE1CneVnGVWjFYNuwG9:-KE1CneVnGVWjFYNuwGA:-327134416) ([raw file](https://github.com/php-coder/mystamps/blob/7a944763c43db171a9a0c30577ce8ac93891dde6/src/main/java/ru/mystamps/web/service/SeriesServiceImpl.java#L166)):*
Do you plan to add unit test for that as part of this issue?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/php-coder/mystamps/364)*

**Comment by cssru** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/main/java/ru/mystamps/web/dao/JdbcSeriesDao.java, line 32 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/364#-KE1C-Cx4AxzHJTJ-ilG:-KE30ov-y2wDVskUvrpw:-499146009) ([raw file](https://github.com/php-coder/mystamps/blob/7a944763c43db171a9a0c30577ce8ac93891dde6/src/main/java/ru/mystamps/web/dao/JdbcSeriesDao.java#L32)):*
Done.

---

*[src/main/java/ru/mystamps/web/dao/impl/JdbcSeriesDaoImpl.java, line 59 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/364#-KE1C9UJgnanoYdqT8Yu:-KE30vRM2fkcjPDkQnPx:-499146009) ([raw file](https://github.com/php-coder/mystamps/blob/7a944763c43db171a9a0c30577ce8ac93891dde6/src/main/java/ru/mystamps/web/dao/impl/JdbcSeriesDaoImpl.java#L59)):*
Done.

---

*[src/main/java/ru/mystamps/web/dao/impl/JdbcSeriesDaoImpl.java, line 154 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/364#-KE1C82iHkdeV6MZ6SgC:-KE30z_-ewKxu5cP1kjg:-499146009) ([raw file](https://github.com/php-coder/mystamps/blob/7a944763c43db171a9a0c30577ce8ac93891dde6/src/main/java/ru/mystamps/web/dao/impl/JdbcSeriesDaoImpl.java#L154)):*
Done.

---

*[src/main/java/ru/mystamps/web/dao/impl/JdbcSeriesDaoImpl.java, line 167 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/364#-KE1CU_s5PjGJlPxRaaG:-KE312LgXFJGFtFzFmSu:-499146009) ([raw file](https://github.com/php-coder/mystamps/blob/7a944763c43db171a9a0c30577ce8ac93891dde6/src/main/java/ru/mystamps/web/dao/impl/JdbcSeriesDaoImpl.java#L167)):*
Done.

---

*[src/main/java/ru/mystamps/web/service/SeriesServiceImpl.java, line 166 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/364#-KE1CneVnGVWjFYNuwG9:-KE3CLm7YtCS1hEuQM6b:-499146009) ([raw file](https://github.com/php-coder/mystamps/blob/7a944763c43db171a9a0c30577ce8ac93891dde6/src/main/java/ru/mystamps/web/service/SeriesServiceImpl.java#L166)):*
Done.

---

*[src/main/resources/sql/series_dao_queries.properties, line 48 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/364#-KE1CeBFMDjVRGb8NK_2:-KE319avsRyCowIQCu-V:-499146009) ([raw file](https://github.com/php-coder/mystamps/blob/7a944763c43db171a9a0c30577ce8ac93891dde6/src/main/resources/sql/series_dao_queries.properties#L48)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/php-coder/mystamps/364)*

**Comment by php-coder** [comment]
Reviewed 4 of 5 files at r2.
Review status: 4 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/main/java/ru/mystamps/web/service/SeriesServiceImpl.java, line 166 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/364#-KE1CneVnGVWjFYNuwG9:-KE6qR3QvtcaJIYjJB2h:-205175946) ([raw file](https://github.com/php-coder/mystamps/blob/7a944763c43db171a9a0c30577ce8ac93891dde6/src/main/java/ru/mystamps/web/service/SeriesServiceImpl.java#L166)):*
??? :-/

---

*[src/test/groovy/ru/mystamps/web/service/SeriesServiceImplTest.groovy, line 21 \[r2\]](https://reviewable.io:443/reviews/php-coder/mystamps/364#-KE6q_YYT22la5dPN15B:-KE6q_YYT22la5dPN15C:-262394567) ([raw file](https://github.com/php-coder/mystamps/blob/63d454d423ff955e0502d2dc9b82ae398f05892f/src/test/groovy/ru/mystamps/web/service/SeriesServiceImplTest.groovy#L21)):*
Move it to other imports from the same package.

---

*[src/test/groovy/ru/mystamps/web/service/SeriesServiceImplTest.groovy, line 574 \[r2\]](https://reviewable.io:443/reviews/php-coder/mystamps/364#-KE6r5X-IpbWkS6GnRUH:-KE6r5X-IpbWkS6GnRUI:-1455218394) ([raw file](https://github.com/php-coder/mystamps/blob/63d454d423ff955e0502d2dc9b82ae398f05892f/src/test/groovy/ru/mystamps/web/service/SeriesServiceImplTest.groovy#L574)):*
Ah.. I forget that we don't have unit tests for this method yet. So, you could just remember it to me :)

---

*[src/test/groovy/ru/mystamps/web/service/SeriesServiceImplTest.groovy, line 576 \[r2\]](https://reviewable.io:443/reviews/php-coder/mystamps/364#-KE6rQ2XTEbuc2e-vU7i:-KE6rQ2XTEbuc2e-vU7j:-427747025) ([raw file](https://github.com/php-coder/mystamps/blob/63d454d423ff955e0502d2dc9b82ae398f05892f/src/test/groovy/ru/mystamps/web/service/SeriesServiceImplTest.groovy#L576)):*
seriesId -> series id
userId -> user id

---

*[src/test/groovy/ru/mystamps/web/service/SeriesServiceImplTest.groovy, line 589 \[r2\]](https://reviewable.io:443/reviews/php-coder/mystamps/364#-KE6r3fv_2mOvguQXbVd:-KE6r3fv_2mOvguQXbVe:400039889) ([raw file](https://github.com/php-coder/mystamps/blob/63d454d423ff955e0502d2dc9b82ae398f05892f/src/test/groovy/ru/mystamps/web/service/SeriesServiceImplTest.groovy#L589)):*
Trailing tabs.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/php-coder/mystamps/364)*

**Comment by cssru** [comment]
*[src/main/java/ru/mystamps/web/service/SeriesServiceImpl.java, line 166 \[r1\]](https://reviewable.io:443/reviews/php-coder/mystamps/364#-KE1CneVnGVWjFYNuwG9:-KEM1at-r5DKCSoXl6jV:-780338898) ([raw file](https://github.com/php-coder/mystamps/blob/7a944763c43db171a9a0c30577ce8ac93891dde6/src/main/java/ru/mystamps/web/service/SeriesServiceImpl.java#L166)):*
Ты спросил - буду ли я писать тест? Отвечаю - сделано ))

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/php-coder/mystamps/364)*

**Comment by cssru** [comment]
Review status: 4 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/test/groovy/ru/mystamps/web/service/SeriesServiceImplTest.groovy, line 21 \[r2\]](https://reviewable.io:443/reviews/php-coder/mystamps/364#-KE6q_YYT22la5dPN15B:-KEM2DT8vnobKv_zBpp4:-499146009) ([raw file](https://github.com/php-coder/mystamps/blob/63d454d423ff955e0502d2dc9b82ae398f05892f/src/test/groovy/ru/mystamps/web/service/SeriesServiceImplTest.groovy#L21)):*
Done.

---

*[src/test/groovy/ru/mystamps/web/service/SeriesServiceImplTest.groovy, line 576 \[r2\]](https://reviewable.io:443/reviews/php-coder/mystamps/364#-KE6rQ2XTEbuc2e-vU7i:-KEM2LYlgbEumzrSDVXU:-499146009) ([raw file](https://github.com/php-coder/mystamps/blob/63d454d423ff955e0502d2dc9b82ae398f05892f/src/test/groovy/ru/mystamps/web/service/SeriesServiceImplTest.groovy#L576)):*
Done.

---

*[src/test/groovy/ru/mystamps/web/service/SeriesServiceImplTest.groovy, line 589 \[r2\]](https://reviewable.io:443/reviews/php-coder/mystamps/364#-KE6r3fv_2mOvguQXbVd:-KEM2OQGkYdWtXMwZ27v:-499146009) ([raw file](https://github.com/php-coder/mystamps/blob/63d454d423ff955e0502d2dc9b82ae398f05892f/src/test/groovy/ru/mystamps/web/service/SeriesServiceImplTest.groovy#L589)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/php-coder/mystamps/364)*

**Comment by php-coder** [comment]
Reviewed 1 of 5 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/php-coder/mystamps/364)*

**Comment by php-coder** [comment]
Merged in cb0bb53d2f47da7a0dd7f27c6d0272633c798007 commit.

**Pull request closed without merging**
