### PR TITLE
Max pwd integ test

### PR DESCRIPTION
**Pull request by benjiyue**

### CODE REVIEW

**Comment by php-coder** [comment]
Good start, but be careful with your permissions -- please, don't commit to `master` and don't merge pull requests next time :) With great power comes great responsibility (c)

**Comment by php-coder** [comment]
I've reverted changes from the master branch. Could you reopen **this** pull request?

**Comment by benjiyue** [comment]
Sorry. I didn't mean to commit to master. After I pushed to my fork I tried clicking on a few thing on the Github website and I thought I was still in my fork. I didn't realize I had permission on the master. I'll be more careful next time

**Comment by php-coder** [comment]
Are you sure that this will pass compilation? I don't see the import for `PASSWORD_MAX_LENGTH` constant, for instance.

**Comment by benjiyue** [comment]
I was not ready to push to master, yet. This whole merging was a mistake.

I tried looking online for a way to reopen this pull request, but can't seem to find how. Any advice?

**Comment by php-coder** [comment]
Ok, I see that we need to clean you branches:

1) there shouldn't be any commits from you in your master. Please, remove them:
```console
$ git checkout master
$ git reset --hard HEAD^
$ git push --force
```

2) now you need to rebase your branch against master that we've just updated:
```console
$ git rebase master MaxPwdIntegTest
$ git push --force
```

**Comment by php-coder** [comment]
> I tried looking online for a way to reopen this pull request, but can't seem to find how. Any advice?

The commands above will rewrite your `MaxPwdIntegTest` branch and maybe it affect the PR, but I'm not sure. If it won't help, just create another PR.

**Pull request merged**
